name: Pull Request Build
# For pull requests: builds and test
on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master
jobs:
  buildAndTestPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.9'
      - name: build and test
        run: ./gradlew assemble --info && ./gradlew check --info
