name: Manual Release Build
# Release builds
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'the version to be released'
        required: true

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    env:
      MAVEN_CENTRAL_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      RELEASE_VERSION: ${{ github.event.inputs.version }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: build test and publish
        run: ./gradlew assemble && ./gradlew check --info
